version: '3'
services:
  nodejs:
    build: .
    ports:
      - "1111:1111"
    networks:
      - app-network
    depends_on:
      - mongo
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx_data/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - nodejs
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
